# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

EXPOSE 5000

WORKDIR /app

COPY . /app/

RUN pip install -r requirements.txt

CMD ["waitress-serve", "--port=5000", "--call", "app:create_app"]
